### ISSUE TITLE
jit.su not responding

### ISSUE THREAD

**Issue by wetneb** [travis-encrypt/travis-encrypt.github.io#1]
The app seems to be broken because jit.su does not respond.

**Comment by zonca** [comment]
@wetneb thanks, changed JSON proxy, see 7eaeaaed4ee2b69166816a4240ba7cf70003facb

**Comment by wetneb** [comment]
@zonca your new JSON proxy is down again

**Comment by zonca** [comment]
any suggestion?

**Comment by wetneb** [comment]
is it really crucial to use a JSONP proxy? I am not familiar with this technology but it seems to me that the API call could be handled directly in JS locally. Sorry for not filing a PR on this, I'm not very confident writing JS code :-(

**Comment by zonca** [comment]
no, that is the problem, no way without a proxy, you cannot get JSON from
another domain.

**Comment by zonca** [comment]
can you find another JSONP proxy?
