### ISSUE TITLE
Use unminified script

### ISSUE THREAD

**Issue by mbrodala** [travis-encrypt/travis-encrypt.github.io#3]
This service provides a security-related function and currently uses a minified script for this. This makes it impossible to review what the script is doing. So I suggest to replace the minified script with the original one and use this on the website. This is essential to make this a trustworthy service.

**Comment by zonca** [comment]
Sure, would you provide a fix via a Pull Request?

**Comment by mbrodala** [comment]
Obviously I can't since I don't have the original source code. ;-)

**Comment by zonca** [comment]
It's a library I didn't write it


Il mer 11 apr 2018, 16:58 Mathias Brodala <notifications@github.com> ha
scritto:

**Comment by zonca** [comment]
@mbrodala would you like to help me maintain this repository? I can give you push access.

I used this:
http://travistidwell.com/jsencrypt/
